# Puerto del microservicio
server.port=8083
spring.application.name=microservicio-pagos
#URL de la base de datos PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
# Usuario de la base de datos
spring.datasource.username=postgres.cjzolzytsccqjudhagdd
#Contraseña
spring.datasource.password=Lolpopo2121@

# Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Esto crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true