spring.application.name=microservicio-pagos
server.port=8083
spring.application.name=microservicio-pagos

# Conexión a Supabase (Usa tus credenciales del docx) [cite: 200]
spring.datasource.url=jdbc:postgresql://[TU_URL_DE_SUPABASE]
spring.datasource.username=postgres
spring.datasource.password=[TU_CONTRASEÑA]

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect