spring.application.name=shopsmart
#Configuración de conexión a Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?
spring.datasource.username=user=postgres.cjzolzytsccqjudhagdd&password=Lolpopo2121@
spring.datasource.password=Lolpopo2121@

# Esto le dice a Spring Boot que cree la tabla automáticamente si no existe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect