server.port=8082
spring.application.name=shopsmart
# URL 
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
# usuario 
spring.datasource.username=postgres.cjzolzytsccqjudhagdd
# Contraseña real 
spring.datasource.password=Lolpopo2121@
# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect